[node]
installers = "dnf,apt,apk,yum"
name = "NodeJS"
description = "NodeJs v12"

[kubectl]
installers = "apt,yum,curl"
name = "Kubectl"
description = "kubectl controls the Kubernetes cluster manager"

[git]
installers = "dnf,pacman,apt,apk,yum"
name = "Git"
description = "Git SVM"

[pip3]
installers = "dnf,pacman,apt,apk,yum"
name = "Pip3"
description = "Pip is the package installer for Python"

[docker-compose]
installers = "curl"
name = "Docker Compose"
description = "Docker Compose is a tool for defining and running multi-container Docker applications"

[gcloud]
installers = "curl"
name = "gCloud"
description = "CLI tool of GCP"

[yarn]
installers = "dnf,pacman,apt,apk,yum"
name = "Yarn"
description = "Fast, reliable, and secure NodeJS dependency management"

[nginx]
installers = "dnf,pacman,apt,apk,yum"
name = "Nginx"
description = "Nginx server"

[atom]
installers = "dnf,pacman,apt,apk,yum"
name = "Atom"
description = "A hackable text editor for the 21st Century"

[helm]
installers = "curl"
name = "Helm"
description = "The package manager for Kubernetes"

[hlf]
installers = "curl"
name = "Fabric"
description = "Hyperledger Fabric"

[docker]
installers = "apt,yum"
name = "Docker"
description = "Docker is a set of platform as a service products that use OS-level virtualization to deliver software in packages called containers"

[eksctl]
installers = "curl"
name = "eksctl"
description = "A simple CLI tool for creating clusters on EKS"

[ctop]
installers = "curl"
name = "cTop"
description = "Top-like interface for container metrics"

[hello]
installers = "dnf,pacman,apt,apk,yum,curl"
name = "Hello"
description = "This is just a sample tool"

[python3]
installers = "dnf,pacman,apt,apk,yum"
name = "Python 3"
description = "Python 3"
